Stat svc
Aleksey01091993/java-explore-with-me pull request #1
Opened 2024-02-18 16:53 UTC by Aleksey01091993

2024-02-18 18:29 UTC, YazykovMikhail reviewed
Обрати внимание, что у тебя не прошли тесты, стоит поправить это сразу

2024-02-18 18:40 UTC, YazykovMikhail reviewed
Обрати внимание на задание, а именно:
"1. Учитывайте многомодульность." - там описывается как должен выглядит проект, в том числе приведена картинка. 

Я тебе скидываю как стоит организовать проект, в соответсвии с заданием. 
![image](https://github.com/Aleksey01091993/java-explore-with-me/assets/92871393/36b127e4-c708-48a2-8010-095fb4545e7a)

Пока у тебя будут полностью реализованы stats-dto и stats-server, stats-client остальные просто main классом внутри для будущего расшироения. 

Вот еще скрин для примера внутреней структуры:
![image](https://github.com/Aleksey01091993/java-explore-with-me/assets/92871393/5d4e78b2-abd8-4aeb-b1fa-5aad371827e2)

2024-02-18 18:45 UTC, YazykovMikhail commented
Так же комииты с описанием "начало", " все закончил" - это не очень, по ним нчиего не понятно какая работа проводилась, что было сделано, у тебя в этом проекте будут много подпроектов и еси у всех будут комиты "начало", " все закончил"  потом по ним будет тяжело понтяно, что где делалось и где можно посмотреть реализацию того или иного функционала

2024-02-22 06:59 UTC, YazykovMikhail requested changes

2024-02-22 06:59 UTC, YazykovMikhail commented on stats/stats-dto/src/main/java/ru/practicum/dto/RequestStatsDto.java
> +package ru.practicum.dto;
u.practicum.названиепроекта.stats.dto

2024-02-22 06:59 UTC, YazykovMikhail commented on stats/stats-dto/src/main/java/ru/practicum/mapper/MapperToStats.java
> +public class MapperToStats {
Маппера тут не должно быть, этот паке независим ни от кого, его дело хранит dto и то бы их брали для пользования.
Это как ты приходишь в магазин за картошкой, картошка ничего не должна знать о супе иои пюре или жаренной картошке, это просто ресурс для испольования. А уже тот кто используется делает с ней все что ему нужно.

2024-02-22 06:59 UTC, YazykovMikhail commented on stats/stats-server/src/main/java/ru/practicum/service/StatsService.java
> +    public ResponseStatsDto add
не надо делать переносы повсеместно, только там где аргументы не помещаются в масимальный размер строки по кодстайлу

```
public ResponseStatsDto add(RequestStatsDto stats) {
        return MapperToStats.toResponseStats(repository.save(MapperToStats.toStats(stats)));
    }
```
поправь везде

2024-02-22 06:59 UTC, YazykovMikhail commented on stats/stats-server/src/main/java/ru/practicum/service/StatsService.java
> +    public List<ResponseGetStatsDto> get
Тут к слову тоже все входит до 140 символов
    public List<ResponseGetStatsDto> get(String strStart, String strEnd, List<String> uris, Boolean unique) {

2024-02-22 06:59 UTC, YazykovMikhail commented on stats/stats-client/src/main/java/ru/practicum/model/Stats.java
> +package ru.practicum.model;
модуль должна быть там же, где и  сервер, ведь модель это класс для хранения в бд. Соотвественно и находится он рядом с бд

2024-02-22 06:59 UTC, YazykovMikhail commented on stats/stats-client/src/main/java/ru/practicum/model/Stats.java
> +
а в модуле stats-client
должен быть класс который иметируют работу кклиента для вызова твоего сервера.

Вот что то типо того:
```

@Slf4j
@Service
public class StatsClient {
	private static final DateTimeFormatter DTF = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

	private final String application;
	private final String statsServiceUri;
	private final ObjectMapper json;
	private final HttpClient httpClient;

	public StatsClient(@Value("${spring.application.name}") String application,
			@Value("${services.stats-service.uri:http://localhost:9090}") String statsServiceUri,
			ObjectMapper json) {
		this.application = application;
		this.statsServiceUri = statsServiceUri;
		this.json = json;
		this.httpClient = HttpClient.newBuilder()
				.connectTimeout(Duration.ofSeconds(2))
				.build();
	}

	public void hit(HttpServletRequest userRequest) {
		EndpointHit hit = EndpointHit.builder()
				.app(application)
				.ip(userRequest.getRemoteAddr())
				.uri(userRequest.getRequestURI())
				.timestamp(LocalDateTime.now())
				.build();

		try {
			HttpRequest.BodyPublisher bodyPublisher = HttpRequest
					.BodyPublishers
					.ofString(json.writeValueAsString(hit));

			HttpRequest hitRequest = HttpRequest.newBuilder()
					.uri(URI.create(statsServiceUri + "/hit"))
					.POST(bodyPublisher)
					.header(HttpHeaders.CONTENT_TYPE, "application/json")
					.header(HttpHeaders.ACCEPT, "application/json")
					.build();

			HttpResponse<Void> response = httpClient.send(hitRequest, HttpResponse.BodyHandlers.discarding());
			log.debug("Response from stats-service: {}", response);
		} catch (Exception e) {
			log.warn("Cannot record hit", e);
		}
	}
	// метод для вызова getStats
}	
```

2024-02-22 06:59 UTC, YazykovMikhail commented on stats/stats-client/src/main/java/ru/practicum/model/Stats.java
> +
Как раз этот клиент и убдет делать запросы к твоему серверу

2024-02-22 07:17 UTC, Aleksey01091993 commented on stats/stats-dto/src/main/java/ru/practicum/dto/RequestStatsDto.java
> +package ru.practicum.dto;
+

2024-02-22 07:17 UTC, Aleksey01091993 commented on stats/stats-dto/src/main/java/ru/practicum/mapper/MapperToStats.java
> +public class MapperToStats {
+

2024-02-22 07:30 UTC, Aleksey01091993 commented on stats/stats-server/src/main/java/ru/practicum/service/StatsService.java
> +    public ResponseStatsDto add
+

2024-02-22 07:30 UTC, Aleksey01091993 commented on stats/stats-server/src/main/java/ru/practicum/service/StatsService.java
> +    public List<ResponseGetStatsDto> get
+

2024-02-22 07:31 UTC, Aleksey01091993 commented on stats/stats-client/src/main/java/ru/practicum/model/Stats.java
> +package ru.practicum.model;
+

2024-02-22 13:24 UTC, Aleksey01091993 commented on stats/stats-client/src/main/java/ru/practicum/model/Stats.java
> +
+

2024-02-22 16:44 UTC, YazykovMikhail approved these changes

2024-02-22 16:57 UTC, merged